# Generated by Django 5.2.17 on 2026-09-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_decriptiom', models.TextField()),
                ('products_price_new', models.FloatField(default=0)),
                ('product_price_old', models.FloatField(default=0)),
                ('base_price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='product_images')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_edited', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
