# Generated by Django 5.2.17 on 2026-09-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products_price_new',
            new_name='product_price_new',
        ),
    ]
